apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: demo
#common configuration shared between all applications
data:
  application.yml: |-
    configserver:
      name:  JHipster Registry
      status: Connected to the JHipster Registry running in Kubernetes
    eureka:
      client:
        initial-instance-info-replication-interval-seconds: 15
        instance-info-replication-interval-seconds: 15
        registry-fetch-interval-seconds: 15
        fetch-registry: true
        register-with-eureka: true
        eureka-service-url-poll-interval-seconds: 15
      instance:
        lease-renewal-interval-in-seconds: 10
        registry-default-open-for-traffic-count: 0
    jhipster:
      security:
        authentication:
          jwt:
            base64-secret: NTliOWM3Yjg0MTg3MTcyODgxZTdlOTc4YTVkYWEwOTdmNmE3ZWRlNmMyOTJlZTQxMDEzNzAxYzU5MjZkNTNhZGYxODNiMjdkNjE3YTQ2NTFjOWNiNjYyYTRjYzE3ZDIyMzkzMw==
    spring:
        security:
          oauth2:
            client:
              provider:
                oidc:
                  issuer-uri: https://dev-7678651.okta.com/oauth2/default
              registration:
                oidc:
                  client-id: 0oa5ni9awaLRtIUJN5d7
                  client-secret: "{cipher}99eff104f875496117367a13c02f03b32a9620732d08977502e073fa5681c8de3e6e8dac238d8e1fe991504c1acad254876140c260e200e1ca404eb911e1c8b0"
  # app specific configuration
  jhipster-registry.yml: |-
    eureka:
      client:
        service-url:
          defaultZone: http://admin:${spring.security.user.password}@jhipster-registry-0.jhipster-registry.demo.svc.cluster.local:8761/eureka/,http://admin:${spring.security.user.password}@jhipster-registry-1.jhipster-registry.demo.svc.cluster.local:8761/eureka/
